name: Deploy
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Flatpak and flatpak-builder
        run: |
          sudo apt update
          sudo apt install flatpak -y
          sudo apt install flatpak-builder -y

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run tests
        run: "deno test"

      - name: Build step
        run: |
          deno compile --target x86_64-unknown-linux-gnu  --allow-read --allow-write --output tcx-ls-linux-x86_64       main.ts
          deno compile --target aarch64-unknown-linux-gnu --allow-read --allow-write --output tcx-ls-linux-arm64        main.ts
          deno compile --target aarch64-apple-darwin      --allow-read --allow-write --output tcx-ls-macos-arm64        main.ts
          deno compile --target x86_64-apple-darwin       --allow-read --allow-write --output tcx-ls-macos-x86_64       main.ts
          deno compile --target x86_64-pc-windows-msvc    --allow-read --allow-write --output tcx-ls-windows-x86_64.exe main.ts

      - name: Add Flathub Repo
        run: |
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build the Flatpak package
        run: |
          cd deployment/flatpak
          #flatpak-builder --user --force-clean --install-deps-from=flathub builddir com.tderflinger.tcx-ls.yml
          flatpak-builder \
            --user \
            --force-clean \
            --install-deps-from=flathub \
            --repo=repo \
            builddir \
            com.tderflinger.tcx-ls.yml

          flatpak build-bundle \
            repo \
            tcx-ls.flatpak \
            com.tderflinger.tcx-ls

      - name: Upload Linux x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-linux-x86_64
          path: ./tcx-ls-linux-x86_64

      - name: Upload Linux arm64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-linux-arm64
          path: ./tcx-ls-linux-arm64

      - name: Upload macOS arm64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-macos-arm64
          path: ./tcx-ls-macos-arm64

      - name: Upload macOS x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-macos-x86_64
          path: ./tcx-ls-macos-x86_64

      - name: Upload Windows x86_64
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-windows-x86_64.exe
          path: ./tcx-ls-windows-x86_64.exe

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: tcx-ls-flatpak
          path: deployment/flatpak/tcx-ls.flatpak

      - name: Create or update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Release latest
          body: Automated release for latest
          make_latest: true
          overwrite_files: true
          files: |
            tcx-ls-linux-x86_64
            tcx-ls-linux-arm64
            tcx-ls-windows-x86_64.exe
            tcx-ls-macos-arm64
            deployment/flatpak/tcx-ls.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

